import fs from 'node:fs';
import path from 'node:path';

export type WrapperRuntime = 'native' | 'node';

export const writeWrapper = (
  wrapperPath: string,
  configDir: string,
  binaryPath: string,
  runtime: WrapperRuntime = 'node'
) => {
  const tweakDir = path.join(path.dirname(configDir), 'tweakcc');
  const execLine = runtime === 'node' ? `exec node "${binaryPath}" "$@"` : `exec "${binaryPath}" "$@"`;
  const envLoader = [
    'if command -v node >/dev/null 2>&1; then',
    '  __cc_mirror_env_file="$(mktemp)"',
    '  node - <<\'NODE\' > "$__cc_mirror_env_file" || true',
    "const fs = require('fs');",
    "const path = require('path');",
    "const dir = process.env.CLAUDE_CONFIG_DIR;",
    "if (!dir) process.exit(0);",
    "const file = path.join(dir, 'settings.json');",
    "const escape = (value) => \"'\" + String(value).replace(/'/g, \"'\\\"'\\\"'\") + \"'\";",
    "try {",
    "  if (fs.existsSync(file)) {",
    "    const data = JSON.parse(fs.readFileSync(file, 'utf8'));",
    "    const env = data && typeof data === 'object' ? data.env : null;",
    "    if (env && typeof env === 'object') {",
    "      for (const [key, value] of Object.entries(env)) {",
    "        if (!key) continue;",
    "        process.stdout.write(`export ${key}=${escape(value)}\\n`);",
    "      }",
    "    }",
    "  }",
    "} catch {",
    "  // ignore malformed settings",
    "}",
    'NODE',
    '  if [[ -s "$__cc_mirror_env_file" ]]; then',
    '    # shellcheck disable=SC1090',
    '    source "$__cc_mirror_env_file"',
    '  fi',
    '  rm -f "$__cc_mirror_env_file" || true',
    'fi',
  ];
  const splash = [
    'if [[ "${CC_MIRROR_SPLASH:-0}" != "0" ]] && [[ -t 1 ]]; then',
    '  if [[ "$*" != *"--output-format"* ]]; then',
    '    __cc_label="${CC_MIRROR_PROVIDER_LABEL:-cc-mirror}"',
    '    __cc_style="${CC_MIRROR_SPLASH_STYLE:-default}"',
    '    __cc_show_label="1"',
    '    printf "\\n"',
    '    case "$__cc_style" in',
    "      zai)",
    "        cat <<'CCMZAI'",
    '',
    '    ███████╗       █████╗ ██╗',
    '    ╚══███╔╝      ██╔══██╗██║',
    '      ███╔╝       ███████║██║',
    '     ███╔╝    ██╗ ██╔══██║██║',
    '    ███████╗  ╚═╝ ██║  ██║██║',
    '    ╚══════╝      ╚═╝  ╚═╝╚═╝',
    '',
    '    ━━━━━━━━━━◆━━━━━━━━━━',
    '      GLM Coding Plan',
    '',
    'CCMZAI',
    '        __cc_show_label="0"',
    '        ;;',
    "      minimax)",
    "        cat <<'CCMMIN'",
    '',
    '    ███╗   ███╗██╗███╗   ██╗██╗███╗   ███╗ █████╗ ██╗  ██╗',
    '    ████╗ ████║██║████╗  ██║██║████╗ ████║██╔══██╗╚██╗██╔╝',
    '    ██╔████╔██║██║██╔██╗ ██║██║██╔████╔██║███████║ ╚███╔╝',
    '    ██║╚██╔╝██║██║██║╚██╗██║██║██║╚██╔╝██║██╔══██║ ██╔██╗',
    '    ██║ ╚═╝ ██║██║██║ ╚████║██║██║ ╚═╝ ██║██║  ██║██╔╝ ██╗',
    '    ╚═╝     ╚═╝╚═╝╚═╝  ╚═══╝╚═╝╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝',
    '',
    '    ━━━━━━━━━━━━━━━━━━◆━━━━━━━━━━━━━━━━━━',
    '           MiniMax-M2.1 ━ AGI for All',
    '',
    'CCMMIN',
    '        __cc_show_label="0"',
    '        ;;',
    "      openrouter)",
    "        cat <<'CCMORT'",
    '',
    '     ██████╗ ██████╗ ███████╗███╗   ██╗',
    '    ██╔═══██╗██╔══██╗██╔════╝████╗  ██║',
    '    ██║   ██║██████╔╝█████╗  ██╔██╗ ██║',
    '    ██║   ██║██╔═══╝ ██╔══╝  ██║╚██╗██║',
    '    ╚██████╔╝██║     ███████╗██║ ╚████║',
    '     ╚═════╝ ╚═╝     ╚══════╝╚═╝  ╚═══╝',
    '    ██████╗  ██████╗ ██╗   ██╗████████╗███████╗██████╗',
    '    ██╔══██╗██╔═══██╗██║   ██║╚══██╔══╝██╔════╝██╔══██╗',
    '    ██████╔╝██║   ██║██║   ██║   ██║   █████╗  ██████╔╝',
    '    ██╔══██╗██║   ██║██║   ██║   ██║   ██╔══╝  ██╔══██╗',
    '    ██║  ██║╚██████╔╝╚██████╔╝   ██║   ███████╗██║  ██║',
    '    ╚═╝  ╚═╝ ╚═════╝  ╚═════╝    ╚═╝   ╚══════╝╚═╝  ╚═╝',
    '',
    '    ━━━━━━━━━━━━━◆━━━━━━━━━━━━━',
    '      One API ━ Any Model',
    '',
    'CCMORT',
    '        __cc_show_label="0"',
    '        ;;',
    "      local)",
    "        cat <<'CCMLOC'",
    '',
    '    ██╗      ██████╗  ██████╗ █████╗ ██╗',
    '    ██║     ██╔═══██╗██╔════╝██╔══██╗██║',
    '    ██║     ██║   ██║██║     ███████║██║',
    '    ██║     ██║   ██║██║     ██╔══██║██║',
    '    ███████╗╚██████╔╝╚██████╗██║  ██║███████╗',
    '    ╚══════╝ ╚═════╝  ╚═════╝╚═╝  ╚═╝╚══════╝',
    '    ██╗     ██╗     ███╗   ███╗███████╗',
    '    ██║     ██║     ████╗ ████║██╔════╝',
    '    ██║     ██║     ██╔████╔██║███████╗',
    '    ██║     ██║     ██║╚██╔╝██║╚════██║',
    '    ███████╗███████╗██║ ╚═╝ ██║███████║',
    '    ╚══════╝╚══════╝╚═╝     ╚═╝╚══════╝',
    '',
    '    ━━━━━━━━━━◆━━━━━━━━━━',
    '      Your Models ━ Your Rules',
    '',
    'CCMLOC',
    '        __cc_show_label="0"',
    '        ;;',
    '      *)',
    "        cat <<'CCMGEN'",
    '',
    '    ██████╗ ██████╗   ━━  M I R R O R',
    '   ██╔════╝██╔════╝',
    '   ██║     ██║     Claude Code Variants',
    '   ██║     ██║     Custom Providers',
    '   ╚██████╗╚██████╗',
    '    ╚═════╝ ╚═════╝',
    '',
    'CCMGEN',
    '        ;;',
    '    esac',
    '    if [[ "$__cc_show_label" == "1" ]]; then',
    '      printf "        %s\\n\\n" "$__cc_label"',
    '    else',
    '      printf "\\n"',
    '    fi',
    '  fi',
    'fi',
  ];
  const content = [
    '#!/usr/bin/env bash',
    'set -euo pipefail',
    `export CLAUDE_CONFIG_DIR="${configDir}"`,
    `export TWEAKCC_CONFIG_DIR="${tweakDir}"`,
    ...envLoader,
    'if [[ "${CC_MIRROR_UNSET_AUTH_TOKEN:-0}" != "0" ]]; then',
    '  unset ANTHROPIC_AUTH_TOKEN',
    'fi',
    ...splash,
    execLine,
    '',
  ].join('\n');
  fs.writeFileSync(wrapperPath, content, { mode: 0o755 });
};
